### ISSUE TITLE
https://github.com/lem0nSec/ShellGhost similarity

### ISSUE THREAD

**Issue by cookpoo78** [vxCrypt0r/Voidmaw#1]
Very nice project, keep it up!
Is it using the same technique as https://github.com/lem0nSec/ShellGhost ?

**Comment by vxCrypt0r** [comment]
I was not aware of the above mentioned project. Both projects have the same end-goal, but they are different. Both use VEH and both use breakpoints for payload control, however:

1.) Payload generation differences:
 * ShellGhost performs static analysis and encrypts ALL the shellcode. If your shellcode is a reflective loader for a converted PE, the payload will not work since the PE file structure will be encrypted and corrupted/invalid, and the self loading will fail. Voidmaw actually executes the payload and masks only the executed assembly with INT3, leaving the rest of the payload untouched. This will not mess up any shellcode variables/data/strings that the loader or the code will later need. After checking the code of ShellGhost, there is an attempt to address this problem, however that won't work in most cases, and the fix mostly addresses the msfvenom exec payload only.

2.) Payload execution differences:
 * ShellGhost execution will break in case the payload spawns a new thread in it's own memory page, since the entrypoint of the newly created thread wll be encrypted. Voidmaw will work with multi-threaded payloads since an instruction has two possible states: masked and clear. If it's masked, the same VEH will handle it with no issue, if it's not masked, execution will resume with no other issues.
 * ShellGhost has the full shellcode in one place in an encrypted state, while Voidmaw has no shellcode at all, since all is masked with INT3, while holding the shellcode encrypted and fragmented in a separate structure.

**Comment by itaymigdal** [comment]
@vxCrypt0r Hey, it's me from my other account. Thank u very much for the detailed answer, you rock! 🏆

**Comment by vxCrypt0r** [comment]
No problem, man. cheers!
